
package p2pFilesharer.webservice.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceReceiver", targetNamespace = "http://server.webservice.p2pFilesharer/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServiceReceiver {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://server.webservice.p2pFilesharer/ServiceReceiver/sendMessageRequest", output = "http://server.webservice.p2pFilesharer/ServiceReceiver/sendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
